#!/bin/bash

path=$(dirname $(realpath $0))
. $path/tree.sh
. $path/option.sh

outfile=""
infiles=""
    
function add_outfile()
{
	outfile=$1
}

function add_infile()
{
	infiles="$infiles $1"
}

declare -a option_tbl0=("-m"			"ARG"		""		"true")
declare -a option_tbl1=("-z"			"ARG"		""		"true")
declare -a option_tbl2=("-r"			"NOARG"		""		"true")
declare -a option_tbl3=("-o"			"ARG" 		""		"add_outfile")
declare -a option_tbl4=("--whole-archive"	"ARG"		""		"add_infile")
declare -a option_tbl5=("--no-whole-archive"	"NOARG"		""		"true")
declare -a option_tbl6=("--start-group"		"PAIR"		"--end-group"	"add_infile")
declare -a option_tbl7=("--emit-relocs"		"NOARG"		""		"true")
declare -a option_tbl8=("--build-id"		"NOARG"		""		"true")
declare -a option_tbl9=("-T"			"ARG"		""		"add_infile")

my_getopt "option_tbl" 10 "add_infile" "$*"


echo "$@" >> log.ld
echo "$infiles -> $outfile" >> log.ld
if [ -z "$outfile" ]; then
	exit
fi
build_construct_tree "ld" "$*" "$outfile" "$infiles"
