#!/bin/bash

path=$(dirname $(realpath $0))
. $path/tree.sh

result=$($path/adapter_gcc $@)
if [ $? -ne 0 ]; then
	exit 1
fi

infile=$(echo "$result" | awk -F ":" '{print $1}')
outfile=$(echo "$result" | awk -F ":" '{print $2}')

echo "$@" >> log.gcc

if [ -z "$outfile" -o -z "$infile" -o -c "$outfile" -o "$infile" == "-" -o -c "$infile" ];then
	exit
fi
echo "$infile -> $outfile" >> log.gcc
build_construct_tree "gcc" "$*" ${outfile} "${infile}"
