#!/bin/bash

path=$(dirname $(realpath $0))
. $path/tree.sh

result=$($path/adapter_gcc $@)

infile=$(echo "$result" | awk -F ":" '{print $1}')
outfile=$(echo "$result" | awk -F ":" '{print $2}')

echo "$@" >> log.gcc

if [ ! -f "$outfile" ];then
	exit
fi
echo "$infile -> $outfile" >> log.gcc
build_construct_tree "gcc" "$*" ${outfile} "${infile}"
