#!/bin/bash

path=$(dirname $(realpath $0))
. $path/comm-func.sh
. $path/tree.sh
. $path/option.sh

infile=""
outfile=""

function add_input_output()
{
	if [ -z "$infile" ]; then
		infile=$1
	else
		outfile=$1
	fi
}

declare -a option_tbl0=("-S"	"NOARG" 	""	"true")
declare -a option_tbl1=("-R"	"ARG"		""	"true")
declare -a option_tbl2=("-O"	"ARG"		""	"true")

my_getopt "option_tbl" 3 "add_input_output" "$*"

if [ -z "$outfile" ]; then
	exit
fi

echo "$@" >> log.objcopy
echo "$infile -> $outfile" >> log.objcopy

build_construct_tree "objcopy" "$*" "$outfile" "$infile"
